import * as React from 'react';
import { storiesOf } from '@storybook/react';

import { AutocompleteDropdown } from './autocomplete-dropdown';


storiesOf('AutocompleteDropdown', module)
  .add('default', () => (
    <AutocompleteDropdown variants={ autocompleteVariants }/>
  ));


const autocompleteVariants = [
  {
    'main_airport_name': null,
    'coordinates': { 'lat': 55.755786, 'lon': 37.617633 },
    'cases': { 'tv': 'Москвой', 'ro': 'Москвы', 'pr': 'Москве', 'vi': 'в Москву', 'da': 'Москве' },
    'name': 'Москва',
    'country_cases': null,
    'country_name': 'Россия',
    'country_code': 'RU',
    'index_strings': ['defaultcity', 'defaultcity', 'maskava', 'maskva', 'mosca', 'moscou', 'moscova', 'moscovo', 'moscow', 'moscú', 'moskau', 'moskou', 'moskova', 'moskow', 'moskva', 'moskwa', 'moszkva', 'μόσχα', 'москва', 'нерезиновая', 'нерезиновая', 'нерезиновск', 'нерезиновск', 'понаехавск', 'понаехавск', 'մոսկվա', 'מוסקבה', 'مسکو', 'موسكو', 'मास्को', 'มอสโก', 'მოსკოვი', 'モスクワ', '莫斯科', '모스크바'],
    'code': 'MOW',
    'state_code': null,
    'type': 'city',
    'weight': 1006321,
  }, {
    'coordinates': { 'lat': 55.414566, 'lon': 37.899494 },
    'name': 'Домодедово',
    'country_cases': null,
    'city_code': 'MOW',
    'cases': null,
    'city_name': 'Москва',
    'country_name': 'Россия',
    'country_code': 'RU',
    'index_strings': ['aeroportul domodedovo moscova', 'defaultcity', 'domodedovo', 'domodedovo internasjonale flyplass', 'domodedovo luchthaven', 'domodedowo', 'domodiedowo', 'letališče moskva domodedovo', 'letisko moskva domodedovo', 'letiště moskva domodedovo', 'maskava', 'maskavas domodedovo lidosta', 'maskva', 'međunarodni aerodrom domodedovo', 'mosca', 'moscou', 'moscova', 'moscovo', 'moscovo - domodedovo', 'moscow', 'moscow domodedovo', 'moscow domodedovo airport', 'moscow domodedovos flygplats', 'moscú', 'moskau', 'moskou', 'moskova', 'moskova domodedovon lentokenttä', 'moskow', 'moskva', 'moskva-domodedovo internationale lufthavn', 'moskwa', 'moszkva', 'moszkva domodedovo repülőtér', 'zračna luka moscow domodedovo', 'μόσχα', 'μόσχα ντομοντέντοβο αεροδρόμιο', 'домодедово', 'домодєдово', 'летище москва домодедово', 'москва', 'нерезиновая', 'нерезиновск', 'понаехавск', 'դոմոդեդովո', 'մոսկվա', 'מוסקבה', 'נמל התעופה מוסקבה דומודאדובו', 'فرودگاه بین‌المللی دوموده‌دوو', 'مسکو', 'مطار دوموديدوڤو موسكو', 'موسكو', 'मास्को', 'मास्को दोमोदेदोवो हवाई अड्डा', 'มอสโก', 'สนามบินโดโมเดโดโว', 'დამაძედოვოს აეროპორტი', 'მოსკოვი', 'モスクワ', '多莫杰多沃机场', '莫斯科', '모스크바'],
    'code': 'DME',
    'state_code': null,
    'type': 'airport',
    'city_cases': { 'tv': 'Москвой', 'ro': 'Москвы', 'pr': 'Москве', 'vi': 'в Москву', 'da': 'Москве' },
    'weight': 613709,
  }, {
    'coordinates': { 'lat': 55.966324, 'lon': 37.416573 },
    'name': 'Шереметьево',
    'country_cases': null,
    'city_code': 'MOW',
    'cases': null,
    'city_name': 'Москва',
    'country_name': 'Россия',
    'country_code': 'RU',
    'index_strings': ['aerodrom šeremetjevo', 'aeroportul internațional sheremetyevo', 'defaultcity', 'maskava', 'maskva', 'mednarodno letališče šeremetjevo', 'medzinárodné letisko sheremetyevo', 'mezinárodní letiště sheremetyevo', 'međunarodna zračna luka sheremetyevo', 'mosca', 'moscou', 'moscova', 'moscovo', 'moscovo - sheremetyevo', 'moscow', 'moscow sheremetyevo', 'moscú', 'moskau', 'moskau-scheremetjewo', 'moskou', 'moskova', 'moskow', 'moskva', 'moskva-sjeremetevo internationale lufthavn', 'moskwa', 'moszkva', 'seremetjevon kansainvälinen lentoasema', 'sheremetyevo', 'sheremetyevo international airport', 'sheremetyevo nemzetközi repülőtér', 'sheremetyevos internationella flygplats', 'sjeremetjevo internasjonale flyplass', 'sjeremetjevo internationale luchthaven', 'szeremietiewo', 'šeremetjevo lidosta', 'μόσχα', 'σερεμέτιεβο διεθνές αεροδρόμιο', 'международно летище шереметево', 'москва', 'нерезиновая', 'нерезиновск', 'понаехавск', 'шереметьево', 'шереметьєво', 'մոսկվա', 'շետեմետևո', 'מוסקבה', 'נמל התעופה הבינלאומי של שרמטייבו', 'فرودگاه بین‌المللی شرمتیوو', 'مسکو', 'مطار شيريميتيفو الدولي', 'موسكو', 'मास्को', 'शेरेमेत्येवो अंतराष्ट्रीय हवाई अड्डा', 'มอสโก', 'สนามบินนานาชาติเชเรเมเตียโว', 'მოსკოვი', 'შერემეწევოს აეროპორტი', 'モスクワ', '莫斯科', '谢列梅捷沃机场', '모스크바'],
    'code': 'SVO',
    'state_code': null,
    'type': 'airport',
    'city_cases': { 'tv': 'Москвой', 'ro': 'Москвы', 'pr': 'Москве', 'vi': 'в Москву', 'da': 'Москве' },
    'weight': 219897,
  }, {
    'coordinates': { 'lat': 55.60315, 'lon': 37.2921 },
    'name': 'Внуково',
    'country_cases': null,
    'city_code': 'MOW',
    'cases': null,
    'city_name': 'Москва',
    'country_name': 'Россия',
    'country_code': 'RU',
    'index_strings': ['aerodrom vnukovo', 'aeroportul vnukovo', 'defaultcity', 'letališče vnukovo', 'letisko vnukovo', 'letiště vnukovo', 'maskava', 'maskva', 'mosca', 'moscou', 'moscova', 'moscovo', 'moscovo - vnukovo', 'moscow', 'moscow vnukovo', 'moscú', 'moskau', 'moskau wnukowo', 'moskou', 'moskova', 'moskow', 'moskva', 'moskva-vnukovo internationale lufthavn', 'moskwa', 'moszkva', 'vnukovo', 'vnukovo airport', 'vnukovo internasjonale flyplass', 'vnukovo lidosta', 'vnukovo luchthaven', 'vnukovo repülőtér', 'vnukovon lentoasema', 'vnukovos flygplats', 'wnukowo', 'zračna luka vnukovo', 'βνούκοβο αεροδρόμιο', 'μόσχα', 'внуково', 'летище внуково', 'москва', 'нерезиновая', 'нерезиновск', 'понаехавск', 'մոսկվա', 'վնուկովո', 'מוסקבה', 'נמל התעופה הבינלאומי ונוקובו', 'فرودگاه بین‌المللی ونوکووا', 'مسکو', 'مطار ڤنوكوڤو', 'موسكو', 'मास्को', 'वनकोवो हवाई अड्डा', 'มอสโก', 'สนามบินวนูโคโว', 'ვნუკოვოს აეროპორტი', 'მოსკოვი', 'モスクワ', '伏努科沃机场', '莫斯科', '모스크바'],
    'code': 'VKO',
    'state_code': null,
    'type': 'airport',
    'city_cases': { 'tv': 'Москвой', 'ro': 'Москвы', 'pr': 'Москве', 'vi': 'в Москву', 'da': 'Москве' },
    'weight': 160938,
  }, {
    'coordinates': { 'lat': 55.5690146, 'lon': 38.1419636 },
    'name': 'Жуковский',
    'country_cases': null,
    'city_code': 'MOW',
    'cases': null,
    'city_name': 'Москва',
    'country_name': 'Россия',
    'country_code': 'RU',
    'index_strings': ['aeroportul international zhukovsky', 'defaultcity', 'maskava', 'maskva', 'mednarodno letališče žukovski', 'medzinárodné letisko zhukovsky', 'mezinárodní letiště zhukovsky', 'međunarodna zračna luka zhukovsky', 'mosca', 'moscou', 'moscova', 'moscovo', 'moscow', 'moscú', 'moskau', 'moskou', 'moskova', 'moskow', 'moskva', 'moskwa', 'moszkva', 'zhukovsky', 'zhukovsky international airport', 'zhukovsky international flyplass', 'zhukovsky internationale lufthavn', 'zhukovsky medjunarodni aerodrom', 'zhukovsky nemzetközi repülőtér', 'zhukovskyn kansainvälinen lentokenttä', 'zhukovskys internationella flygplats', 'zjoekovski internationale luchthaven', 'žukovskas lidosta', 'ζουκόφσκι διεθνές αεροδρόμιο', 'μόσχα', 'жуковский', 'международно летище москва жуковски', 'москва', 'нерезиновая', 'нерезиновск', 'понаехавск', 'ժուկովսկի', 'մոսկվա', 'מוסקבה', 'נמל התעופה ז\'וקובסקי הבינלאומי', 'فرودگاه رامنسکویه', 'مسکو', 'مطار زهكوڤسكي الدولي', 'موسكو', 'मास्को', 'ज़्हुकोवस्की अंतराष्ट्रीय हवाई अड्डा', 'มอสโก', 'მოსკოვი', 'ჟუკოვსკის აეროპორტი', 'モスクワ', '莫斯科', '모스크바'],
    'code': 'ZIA',
    'state_code': null,
    'type': 'airport',
    'city_cases': { 'tv': 'Москвой', 'ro': 'Москвы', 'pr': 'Москве', 'vi': 'в Москву', 'da': 'Москве' },
    'weight': 2747,
  }, {
    'main_airport_name': 'Мостар',
    'coordinates': { 'lat': 43.285557, 'lon': 17.846666 },
    'cases': { 'tv': 'Мостаром', 'ro': 'Мостара', 'pr': 'Мостаре', 'vi': 'в Мостар', 'da': 'Мостару' },
    'name': 'Мостар',
    'country_cases': null,
    'country_name': 'Босния и Герцеговина',
    'country_code': 'BA',
    'index_strings': ['mostar', 'mostara', 'μόσταρ', 'мостар', 'мостар', 'մոստար', 'מוסטר', 'موستار', 'मोस्टर', 'მოსტარი', 'モスタール', '莫斯塔尔', '莫斯塔爾', '모스타르'],
    'code': 'OMO',
    'state_code': null,
    'type': 'city',
    'weight': 3284,
  }, {
    'main_airport_name': 'Мушёэн',
    'coordinates': { 'lat': 65.78439, 'lon': 13.218328 },
    'cases': { 'tv': 'Мушёэном', 'ro': 'Мушёэна', 'pr': 'Мушёэне', 'vi': 'в Мушёэн', 'da': 'Мушёэну' },
    'name': 'Мушеэн',
    'country_cases': null,
    'country_name': 'Норвегия',
    'country_code': 'NO',
    'index_strings': ['mosjoen', 'mosjoen kjaerstad', 'mosjøen', 'mūšēene', 'μόστζον', 'мушоен', 'мушьоен', 'мушеэн', 'мушеэн', 'մուշյոեն', 'מוסיואן', 'موسچوين', 'موشن', 'มอสโจน', 'მუშოენი', 'モーシェーン', '莫舍恩', '모조엔'],
    'code': 'MJF',
    'state_code': null,
    'type': 'city',
    'weight': 192,
  }, {
    'main_airport_name': 'Dixsept Rosado',
    'coordinates': { 'lat': -5.166667, 'lon': -37.25 },
    'cases': null,
    'name': 'Моссоро',
    'country_cases': null,
    'country_name': 'Бразилия',
    'country_code': 'BR',
    'index_strings': ['dixsept rosado', 'mossoro', 'mossoró', 'моссоро', '‪mossoró‬‏', 'モソロ', '莫索罗', '莫索羅'],
    'code': 'MVF',
    'state_code': 'RN',
    'type': 'city',
    'weight': 17,
  }, {
    'coordinates': { 'lat': 33.943398, 'lon': -118.40828 },
    'name': 'Лос-Анджелес',
    'country_cases': null,
    'city_code': 'LAX',
    'cases': null,
    'city_name': 'Лос-Анджелес',
    'country_name': 'США',
    'country_code': 'US',
    'index_strings': ['aeroportul internațional los angeles', 'los andželas', 'los angeles', 'los angeles flyplass', 'los angeles internacional', 'los angeles international', 'los angeles international airport', 'los angeles internationale luchthaven', 'los angeles internationale lufthavn', 'los angeles internationella flygplats', 'los angeles nemzetközi repülőtér', 'los angelesin kansainvälinen lentokenttä', 'los anđeles', 'los anđeles međunarodni aerodrom', 'los ángeles', 'losandželosa', 'losandželosas starptautiskā lidosta', 'mednarodno letališče los angeles', 'medzinárodné letisko los angeles', 'mezinárodní letiště v los angeles', 'međunarodna zračna luka los angeles', 'λος άντζελες', 'λος άντζελες διεθνές αεροδρόμιο', 'лос анджелис', 'лос-анджелес', 'международно летище лос анджелис', 'լոս անջելոս', 'լոս անջելոս միջազգային', 'לוס אנג\'לס', 'נמל התעופה הבינלאומי של לוס אנג\'לס', 'فرودگاه بین‌المللی لس‌آنجلس', 'لس‌آنجلس', 'لوس أنجلوس', 'مطار لوس أنجلوس الدولى', 'लॉस एंजेलिस', 'लॉस एंजेल्स अंतरराष्ट्रीय हवाई अड्डा', 'ลอสแอนเจลิส', 'สนามบินนานาชาติลอสแอนเจลิส', 'ლოს ანჯელესი', 'ლოს-ანჯოლოსის საერთაშორისო აეროპორტი', 'ロサンゼルス', '洛杉矶', '洛杉矶机场', '洛杉磯', '로스앤젤레스'],
    'code': 'LAX',
    'state_code': 'CA',
    'type': 'airport',
    'city_cases': {
      'tv': 'Лос-Анджелесом',
      'ro': 'Лос-Анджелеса',
      'pr': 'Лос-Анджелесе',
      'vi': 'в Лос-Анджелес',
      'da': 'Лос-Анджелесу',
    },
    'weight': 1471965,
  }, {
    'main_airport_name': null,
    'coordinates': { 'lat': 34.0522342, 'lon': -118.2436849 },
    'cases': {
      'tv': 'Лос-Анджелесом',
      'ro': 'Лос-Анджелеса',
      'pr': 'Лос-Анджелесе',
      'vi': 'в Лос-Анджелес',
      'da': 'Лос-Анджелесу',
    },
    'name': 'Лос-Анджелес',
    'country_cases': null,
    'country_name': 'США',
    'country_code': 'US',
    'index_strings': ['los andželas', 'los angeles', 'los anđeles', 'los ángeles', 'losandželosa', 'λος άντζελες', 'лос анджелис', 'лос-анджелес', 'լոս անջելոս', 'לוס אנג\'לס', 'لس‌آنجلس', 'لوس أنجلوس', 'लॉस एंजेलिस', 'ลอสแอนเจลิส', 'ლოს ანჯელესი', 'ロサンゼルス', '洛杉矶', '洛杉磯', '로스앤젤레스'],
    'code': 'LAX',
    'state_code': 'CA',
    'type': 'city',
    'weight': 1503614,
  }, {
    'main_airport_name': 'Ош',
    'coordinates': { 'lat': 40.60769, 'lon': 72.78648 },
    'cases': { 'tv': 'Ошем', 'ro': 'Оша', 'pr': 'Оше', 'vi': 'в Ош', 'da': 'Ошу' },
    'name': 'Ош',
    'country_cases': null,
    'country_name': 'Киргизия',
    'country_code': 'KG',
    'index_strings': ['os', 'osh', 'osj', 'oš', 'oša', 'ος', 'ош', 'ош', 'օշ', 'אוש', 'أوش', 'اوش', 'ओश', 'ออช', 'ოშ', 'オシ', '奥什', '奧什', '오시'],
    'code': 'OSS',
    'state_code': null,
    'type': 'city',
    'weight': 1646803,
  }, {
    'main_airport_name': 'Кос',
    'coordinates': { 'lat': 36.793056, 'lon': 27.095278 },
    'cases': { 'tv': 'Косом', 'ro': 'Коса', 'pr': 'Косе', 'vi': 'в Кос', 'da': 'Косу' },
    'name': 'Кос',
    'country_cases': null,
    'country_name': 'Греция',
    'country_code': 'GR',
    'index_strings': ['istankoy', 'kos', 'kosa', 'kosz', 'kós', 'κως', 'кос', 'кос', 'կոս', 'קוס', 'جزیره کس', 'كوس', 'कोस', 'เคโอส', 'კოსი', '科斯'],
    'code': 'KGS',
    'state_code': null,
    'type': 'city',
    'weight': 81842,
  }, {
    'main_airport_name': 'Сибао (Сантьяго)',
    'coordinates': { 'lat': 19.401829, 'lon': -70.60208 },
    'cases': { 'tv': 'Сантьяго', 'ro': 'Сантьяго', 'pr': 'Сантьяго', 'vi': 'в Сантьяго', 'da': 'Сантьяго' },
    'name': 'Сантьяго',
    'country_cases': null,
    'country_name': 'Доминиканская Республика',
    'country_code': 'DO',
    'index_strings': ['santiago', 'santiago', 'santiago de los caballeros', 'santjago', 'σαντιάγο', 'сантьяго', 'сантяго', 'сибао (сантьяго)', 'սանտյագո դե լոս տրեինտա կաբալյերոս', 'סנטיאגו דה לוס קביירוס', 'سانتياغو', 'سانتیاگو ده لوس کابایروس', 'सैंटियागो', 'ซานเตียโก', 'სანტიაგო', 'サンチアゴ', '圣地亚哥', '聖地牙哥', '산티아고'],
    'code': 'STI',
    'state_code': null,
    'type': 'city',
    'weight': 48694,
  }, {
    'main_airport_name': 'Онтарио',
    'coordinates': { 'lat': 34.05, 'lon': -117.64 },
    'cases': { 'tv': 'Онтарио', 'ro': 'Онтарио', 'pr': 'Онтарио', 'vi': 'в Онтарио', 'da': 'Онтарио' },
    'name': 'Онтарио',
    'country_cases': null,
    'country_name': 'США',
    'country_code': 'US',
    'index_strings': ['los angeles', 'los angeles', 'ontarijas', 'ontario', 'ontario, california', 'ontário', 'οντάριο', 'лос-анджелес', 'лос-анджелес', 'онтарио', 'онтарио', 'онтаріо', 'օնտարիո', 'אונטריו', 'أونتاريو', 'انتاریو، کالیفرنیا', 'ओंटारियो', 'ออนแทรีโอ', 'ონტარიო', 'オンタリオ', '安大略', '洛杉矶', '洛杉矶', '온타리오'],
    'code': 'ONT',
    'state_code': 'CA',
    'type': 'city',
    'weight': 22750,
  }, {
    'coordinates': { 'lat': 38.74228, 'lon': -90.36587 },
    'name': 'Ламберт',
    'country_cases': null,
    'city_code': 'STL',
    'cases': null,
    'city_name': 'Сент-Луис',
    'country_name': 'США',
    'country_code': 'US',
    'index_strings': ['aeroportul internațional st. louis lambert', 'lambert-st louis', 'lambert-st. louis internasjonale flyplass', 'lambert-st. louis international airport', 'lambert-st. louis internationale luchthaven', 'lambert-st. louis internationella flygplats', 'lambert-st. louis nemzetközi repülőtér', 'lambert-st. medzinárodné letisko louis', 'lambert-st. mezinárodní letiště louis', 'lambert–st. louis internationale lufthavn', 'lambert–st. louisin kansainvälinen lentoasema', 'lembērtas – sentluisas starptautiskā lidosta', 'mednarodno letališče lambert-st. louis', 'međunarodna zračna luka lambert-st. louis', 'saint louis', 'sent luis', 'sent luisas', 'sentluisa', 'st louis', 'st. louis', 'st. louis lambert int\'l', 'st. louis lambert medjunarodni aerodrom', 'stasiun louis', 'λάμπερτ-σαιντ λούις διεθνές αεροδρόμιο', 'σαιντ λούις', 'ламберт', 'международно летище ламбърт сейнт луис', 'сейнт луис', 'сент-луис', 'сент-луїс', 'լամբերտ', 'սենթ լուիս', 'נמל התעופה הבינלאומי למברט. סנט לואיס', 'סנט לואיס', 'سانت لويس', 'سنت لوئیس، میزوری', 'فرودگاه بین‌المللی لامبرت-ست لوی', 'مطار لامبرت - سانت لويس الدولي', 'लैम्बर्ट सेंट. लुई अंतरराष्ट्रीय हवाई अड्डा', 'सेंट लूइस', 'สนามบินแลมเบิร์ต', 'เซนต์หลุยส์', 'ლამბერტ-სტ. ლუი საერთაშორისო აეროპორტი', 'სენტ-ლუსი', 'セントルイス', '圣路易斯', '圣路易斯机场', '聖路易斯', '세인트루이스'],
    'code': 'STL',
    'state_code': 'MO',
    'type': 'airport',
    'city_cases': {
      'tv': 'Сент-Луисом',
      'ro': 'Сент-Луиса',
      'pr': 'Сент-Луисе',
      'vi': 'в Сент-Луис',
      'da': 'Сент-Луису',
    },
    'weight': 43921,
  }, {
    'main_airport_name': 'Леон',
    'coordinates': { 'lat': 20.985699, 'lon': -101.479 },
    'cases': { 'tv': 'Леоном', 'ro': 'Леона', 'pr': 'Леоне', 'vi': 'в Леон', 'da': 'Леону' },
    'name': 'Леон',
    'country_cases': null,
    'country_name': 'Мексика',
    'country_code': 'MX',
    'index_strings': ['leon', 'leon/guanajuato', 'león', 'león de los aldama', 'león/guanajuato', 'līona', 'silao', 'λεόν/γκουαναχουάτο', 'леон', 'леон', 'լեոն դե լոս ալդամա', 'לאון/ גואנאחואטו', 'لئون، گوآناخوآتو', 'ليون/ جواناواتو', 'लीओन', 'ซิเลา', 'ლეონი', 'レオン・デ・ロス・アルダマ', '莱昂'],
    'code': 'BJX',
    'state_code': null,
    'type': 'city',
    'weight': 15409,
  }, {
    'coordinates': { 'lat': 39.12417, 'lon': -94.59194 },
    'name': 'Даунтаун',
    'country_cases': null,
    'city_code': 'MKC',
    'cases': null,
    'city_name': 'Канзас-Сити',
    'country_name': 'США',
    'country_code': 'US',
    'index_strings': ['aeroportul charles b. wheeler downtown', 'charles b. wheeler belvárosi repülőtér', 'charles b. wheeler downtown airport', 'charles b. wheeler downtown lidosta', 'charles b. wheeler downtown lufthavn', 'charles b. wheeler downtowns flygplats', 'charles b. wheeler flyplass', 'charles b. wheeler luchthaven', 'charles b. wheelerin lentokenttä', 'charles b.wheeler downtown aerodrom', 'kansas city', 'kansas city c.b. wheeler downtown', 'kansas city downtown', 'kansas city, missouri', 'kanzas sitis', 'kanzassitija', 'kommunaler flughafen downtown', 'kota kansas', 'letališče charles b. wheeler downtown', 'letisko downtown charles b. wheeler', 'letiště downtown charles b. wheeler', 'lungsod ng kansas', 'thành phố kansas', 'zračna luka charles b. wheeler downtown', 'κάνσας σίτι', 'τσαρλς μπ. γουίλερ νταουντάουν αεροδρόμιο', 'даунтаун', 'канзас сити', 'канзас-сити', 'канзас-сіті', 'летище чарлз б. уилър даунтаун', 'դաունթաուն', 'կանզաս սիթի', 'נמל התעופה של צ\'רלס ב וילר', 'קנזס סיטי', 'فرودگاه چارلز بول ویلر', 'كانساس سيتي', 'مطار تشارلز ب. ويلر داونتاون', 'کانزاس‌سیتی، میزوری', 'कान्सास सिटी', 'चार्ल्स बी. व्हीलर डाउनटाउन हवाई अड्डा', 'แคนซัสซิตี้', 'แคนซัสซิตี้ อินเตอร์เนชั่นแนล', 'დაუნთაუნის აეროპორტი', 'კანზას სიტი', 'カンザスシティ', 'カンザスシティ・ ダウンタウン空港', '堪萨斯城', '堪薩斯城', '찰스 b. 휠러 다운타운 공항', '캔자스시티'],
    'code': 'MKC',
    'state_code': 'MO',
    'type': 'airport',
    'city_cases': {
      'tv': 'Канзас-Сити',
      'ro': 'Канзас-Сити',
      'pr': 'Канзас-Сити',
      'vi': 'в Канзас-Сити',
      'da': 'Канзас-Сити',
    },
    'weight': 34906,
  }, {
    'coordinates': { 'lat': 28.488056, 'lon': -16.345982 },
    'name': 'Норте',
    'country_cases': null,
    'city_code': 'TCI',
    'cases': null,
    'city_name': 'Тенерифе',
    'country_name': 'Испания',
    'country_code': 'ES',
    'index_strings': ['aeroportul tenerife nord', 'aeropuerto de tenerife norte los rodeos', 'letališče tenerife sever', 'letisko tenerife sever', 'letiště severní tenerife', 'norte los rodeos', 'santa cruz', 'santa cruz de tenerife', 'severni tenerife aerodrom', 'tenerife', 'tenerife nord flyplass', 'tenerife nord lufthavn', 'tenerife norte', 'tenerife norte los rodeos', 'tenerife north airport', 'tenerife norths flygplats', 'tenerifenorte-noord luchthaven', 'teneriffa', 'teneriffa nord', 'teneriffan pohjoinen lentoasema', 'teneriffe', 'tenerifė', 'teneryfa', 'ziemeļtenerifes starptautiskā lidosta', 'zračna luka tenerife north', 'észak tenerife repülőtér', 'τενερίφη', 'τενερίφη βόρεια αεροδρόμιο', 'летище тенерифе', 'норте', 'тенерифе', 'նորտե լոս ռոդեոս', 'տեներիֆե', 'טנריף', 'נמל התעופה טנריף צפון', 'تنريفي', 'تنریف', 'فرودگاه تنریف شمالی', 'مطار تنريفي نورث', 'टेनेरिफ नॉर्थ हवाई अड्डा', 'तेनरीफ़', 'สนามบินเทเนริเฟนอร์เต', 'เทเนริเฟ', 'ნორტეს აეროპორტი', 'ტენერიფე', 'サンタクルスデテネリフェ', '圣克鲁斯-德特内里费', '特内里费', '特内里费北机场', '聖克魯斯省', '산타크루스데 테네리페'],
    'code': 'TFN',
    'state_code': null,
    'type': 'airport',
    'city_cases': { 'tv': 'Тенерифе', 'ro': 'Тенерифе', 'pr': 'Тенерифе', 'vi': 'на Тенерифе', 'da': 'Тенерифе' },
    'weight': 13130,
  }, {
    'main_airport_name': 'Гуеджотсинго',
    'coordinates': { 'lat': 19.135, 'lon': -98.3675 },
    'cases': { 'tv': 'Пуэблой', 'ro': 'Пуэблы', 'pr': 'Пуэбле', 'vi': 'в Пуэблу', 'da': 'Пуэбла' },
    'name': 'Пуэбла',
    'country_cases': null,
    'country_name': 'Мексика',
    'country_code': 'MX',
    'index_strings': ['puebla', 'puebla de los angeles', 'puebla de zaragoza', 'πουέμπλα', 'гуеджотсинго', 'пуебла', 'пуэбла', 'պուեբլա', 'פואבלה', 'بويبلا', 'پوئبلا٬ پوئبلا', 'प्वेब्ला', 'ปูเอบลา', 'პუბლა', 'プエブラ', '普埃布拉', '푸에블라'],
    'code': 'PBC',
    'state_code': null,
    'type': 'city',
    'weight': 3170,
  }, {
    'main_airport_name': 'Бартоломео-Лисандро',
    'coordinates': { 'lat': -21.75, 'lon': -41.3 },
    'cases': {
      'tv': 'Кампус-дус-Гойтаказисом',
      'ro': 'Кампус-дус-Гойтаказиса',
      'pr': 'Кампус-дус-Гойтаказисе',
      'vi': 'в Кампус-дус-Гойтаказис',
      'da': 'Кампус-дус-Гойтаказису',
    },
    'name': 'Кампус-дус-Гойтаказис',
    'country_cases': null,
    'country_name': 'Бразилия',
    'country_code': 'BR',
    'index_strings': ['campos', 'campos dos goitacazes', 'campos dos goytacazes', 'kampos dos gojtakazes', 'kampusa dos goitakazesa', 'κάμπος', 'бартоломео-лисандро', 'кампус дус гойтаказиш', 'кампус-дус-гойтаказис', 'кампус-дус-гойтаказіс', 'կամպոս', 'קאמפוס', 'كامبوس', 'کمپس', 'कम्पोस', 'กัมโปส', 'კამპოსი', 'カンポス・ドス・ゴイタカゼス', '坎波斯'],
    'code': 'CAW',
    'state_code': 'RJ',
    'type': 'city',
    'weight': 961,
  },
];
